# fly.toml app configuration file generated for dmusil-playground on 2023-11-21T14:50:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dmusil-playground"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
[build]
  dockerfile = "Playground/Dockerfile"

